name: Fetch Issue Details for Public Scrumboard

on:
  schedule:
    - cron: '*/10 * * * *'  # Läuft alle 10 Minuten
  workflow_dispatch:

jobs:
  fetch_issue_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Issue Details from GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_GITHUB }}
        run: |
          echo "==== Sende API-Anfrage ===="
          curl -X POST \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d @- <<EOF | tee response.json
          {
            "query": "query FetchIssueDetails(\$owner: String!, \$repo: String!, \$issueNumber: Int!) {
              repository(owner: \$owner, name: \$repo) {
                issue(number: \$issueNumber) {
                  title
                  number
                  url
                  state
                  createdAt
                  updatedAt
                  closedAt
                  author {
                    login
                    avatarUrl
                  }
                  assignees(first: 5) {
                    nodes {
                      login
                      avatarUrl
                    }
                  }
                  labels(first: 10) {
                    nodes {
                      name
                      color
                    }
                  }
                  milestone {
                    title
                    dueOn
                  }
                  projectItems(first: 5) {
                    nodes {
                      fieldValues(first: 10) {
                        nodes {
                          __typename
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldDateValue {
                            date
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }",
            "variables": {
              "owner": "twodarkk",
              "repo": "streamercards",
              "issueNumber": 29
            }
          }
          EOF
          
          echo "==== API-Response ausgeben ===="
          cat response.json

      - name: Process API Response and Create issue_details.json
        run: |
          jq 'if .data.repository.issue then 
                {
                  title: .data.repository.issue.title,
                  number: .data.repository.issue.number,
                  url: .data.repository.issue.url,
                  state: .data.repository.issue.state,
                  created_at: .data.repository.issue.createdAt,
                  updated_at: .data.repository.issue.updatedAt,
                  closed_at: .data.repository.issue.closedAt,
                  author: { 
                    login: .data.repository.issue.author.login, 
                    avatar_url: .data.repository.issue.author.avatarUrl 
                  },
                  assignees: (if .data.repository.issue.assignees.nodes | length > 0 
                              then [.data.repository.issue.assignees.nodes[] | { login: .login, avatar_url: .avatarUrl }]
                              else [] end),
                  labels: (if .data.repository.issue.labels.nodes | length > 0 
                           then [.data.repository.issue.labels.nodes[] | { name: .name, color: .color }]
                           else [] end),
                  milestone: (if .data.repository.issue.milestone 
                              then { title: .data.repository.issue.milestone.title, due_on: .data.repository.issue.milestone.dueOn }
                              else null end),
                  status: (if (.data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Status") | .name)? 
                           then .data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Status") | .name 
                           else null end),
                  priority: (if (.data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Priorität") | .name)? 
                             then .data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Priorität") | .name 
                             else null end),
                  start_date: (if (.data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Start-Datum") | .date)? 
                               then .data.repository.issue.projectItems.nodes[].fieldValues.nodes[] | select(.field.name == "Start-Datum") | .date 
                               else null end)
                }
              else {} end' response.json > issue_details.json
          
          echo "==== Generierte issue_details.json ===="
          cat issue_details.json

      - name: Commit and Push Issue Details
        run: |
          if [ -s issue_details.json ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add issue_details.json
            git commit -m "Updated issue details JSON" || echo "No changes to commit"
            git push
          else
            echo "issue_details.json ist leer, nichts zu committen."
          fi
