name: Fetch Issues from GitHub Project

on:
  workflow_dispatch:

jobs:
  fetch_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Erstelle GraphQL-Query als Datei
        run: |
          cat > query.json <<EOF
          {
            "query": "query {
               node(id: \\"PVT_kwHOAcHVqM4AzEVA\\") {
                 ... on ProjectV2 {
                   items(first: 10) {
                     nodes {
                       content {
                         ... on Issue {
                           title
                           number
                           url
                         }
                       }
                       fieldValues(first: 20) {
                         nodes {
                           __typename
                           ... on ProjectV2ItemFieldSingleSelectValue {
                             name
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldTextValue {
                             text
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldNumberValue {
                             number
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldDateValue {
                             date
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                         }
                       }
                     }
                   }
                 }
               }
             }"
          }
          EOF

      - name: Fetch Issues from GitHub Project
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_GITHUB }}
        run: |
          echo "==== Sende API-Anfrage ===="
          curl -X POST \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               --url "https://api.github.com/graphql" \
               --data @query.json | tee response.json

      - name: Zeige API-Response
        run: cat response.json
