name: Fetch Issues for Public Scrumboard

on:
  schedule:
    - cron: '*/10 * * * *'  # Läuft alle 10 Minuten
  workflow_dispatch:

jobs:
  fetch_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Erstelle GraphQL-Query als Datei
        run: |
          cat > query.json <<EOF
          {
            "query": "query {
               node(id: \\"PVT_kwHOAcHVqM4AzEVA\\") {
                 ... on ProjectV2 {
                   items(first: 10) {
                     nodes {
                       content {
                         ... on Issue {
                           title
                           number
                           url
                         }
                       }
                       fieldValues(first: 20) {
                         nodes {
                           __typename
                           ... on ProjectV2ItemFieldSingleSelectValue {
                             name
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldTextValue {
                             text
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldNumberValue {
                             number
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                           ... on ProjectV2ItemFieldDateValue {
                             date
                             field {
                               ... on ProjectV2FieldCommon {
                                 name
                               }
                             }
                           }
                         }
                       }
                     }
                   }
                 }
               }
             }"
          }
          EOF

      - name: Fetch Issues from GitHub Project
        env:
          GITHUB_TOKEN: ${{ secrets.PAGE_GITHUB }}
        run: |
          echo "==== Sende API-Anfrage ===="
          curl -X POST \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               --url "https://api.github.com/graphql" \
               --data @query.json | tee response.json

      - name: Process API Response and Create issues.json
        run: |
          jq 'if .data.node.items.nodes then .data.node.items.nodes | map({
              title: .content.title,
              number: .content.number,
              url: .content.url,
              status: (.fieldValues.nodes[]? | select(.field.name == "Status") | .name // "Unbekannt"),
              priority: (.fieldValues.nodes[]? | select(.field.name == "Priorität") | .name // "Keine"),
              start_date: (.fieldValues.nodes[]? | select(.field.name == "Start-Datum") | .date // "Kein Datum")
          }) else [] end' response.json > issues.json
          
          echo "==== Generierte issues.json ===="
          cat issues.json


      - name: Commit and Push Issues Data
        run: |
          if [ -s issues.json ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add issues.json
            git commit -m "Updated issues JSON" || echo "No changes to commit"
            git push
          else
            echo "issues.json ist leer, nichts zu committen."
          fi
